#include <cv.h>
#include <cxcore.h>
#include <highgui.h>
#include <iostream>
#include <stdlib.h>
#include <string>
#include <conio.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <cv.h>
#include <highgui.hpp> 
#include <cxcore.h>
#include <tchar.h> 